# Generated by Django 5.0.6 on 2024-05-13 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='body',
            new_name='text',
        ),
    ]
